"""auto-vote

Revision ID: 526e79529369
Revises: 94527c2ce769
Create Date: 2025-05-04 22:14:44.035302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526e79529369'
down_revision: Union[str, None] = '94527c2ce769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("votes",
                    sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
                    sa.Column("post_id", sa.Integer(), nullable=False),
                    sa.Column("user_id", sa.Integer(), nullable=False),
                    sa.Column("dir", sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ),
                    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
                    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("votes")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
